import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, BarChart3, Database, Download, FileDown, GitCompare, Heart, LayoutDashboard, ListChecks, Moon, PackageSearch, Plus, Search, Settings, Star, TableProperties, Trash2, UploadCloud } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './index.css';
import { sampleParts } from './data/sampleParts';
import { emptyFilters, filterParts, summarize } from './lib/normalizer';
import { parseFiles } from './lib/parser';
import { downloadText, toCsv } from './lib/exporters';
import { loadFavorites, loadProject, loadSettings, saveFavorites, saveProject, saveSettings } from './lib/storage';
import { AppSettings, FilterState, ImportedLibrary, Part, ProjectItem, View } from './lib/types';
import { Badge, Button, Card, Input, QualityBadge, Select } from './components/ui';

const tabs: { id: View; label: string; icon: React.ElementType }[] = [
  { id: 'import', label: 'Import', icon: UploadCloud }, { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'explorer', label: 'Bauteil-Explorer', icon: PackageSearch }, { id: 'categories', label: 'Kategorien', icon: TableProperties }, { id: 'missing', label: 'Fehlende Daten', icon: AlertTriangle }, { id: 'favorites', label: 'Favoriten', icon: Heart }, { id: 'project', label: 'Projektliste', icon: ListChecks }, { id: 'compare', label: 'Vergleich', icon: GitCompare }, { id: 'settings', label: 'Einstellungen', icon: Settings }
];
const colors = ['#2563eb', '#0891b2', '#059669', '#d97706', '#dc2626', '#7c3aed', '#4f46e5', '#0f766e'];

function App() {
  const [view, setView] = useState<View>('import');
  const [library, setLibrary] = useState<ImportedLibrary>({ parts: sampleParts, sourceFiles: ['Lokale Beispieldaten'], tables: [], importedAt: new Date().toISOString(), symbolLibraries: [...new Set(sampleParts.map(p => p.symbolLibrary).filter(Boolean) as string[])], footprintLibraries: [...new Set(sampleParts.map(p => p.footprintLibrary).filter(Boolean) as string[])] });
  const [filters, setFilters] = useState<FilterState>(emptyFilters());
  const [selected, setSelected] = useState<Part | undefined>();
  const [favorites, setFavorites] = useState(loadFavorites);
  const [project, setProject] = useState<ProjectItem[]>(loadProject);
  const [compareIds, setCompareIds] = useState<string[]>([]);
  const [settings, setSettings] = useState<AppSettings>(loadSettings);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>();
  const parts = library.parts;
  const filtered = useMemo(() => filterParts(parts, filters), [parts, filters]);
  const stats = useMemo(() => summarize(parts), [parts]);
  useEffect(() => { document.documentElement.classList.toggle('dark', settings.darkMode); saveSettings(settings); }, [settings]);
  useEffect(() => saveFavorites(favorites), [favorites]);
  useEffect(() => saveProject(project), [project]);
  const toggleFavorite = (id: string) => setFavorites((f) => f.includes(id) ? f.filter(x => x !== id) : [...f, id]);
  const addProject = (id: string) => setProject((p) => p.some(x => x.partId === id) ? p : [...p, { partId: id, note: '', addedAt: new Date().toISOString() }]);
  const toggleCompare = (id: string) => setCompareIds((ids) => ids.includes(id) ? ids.filter(x => x !== id) : ids.length < 5 ? [...ids, id] : ids);
  const importFiles = async (files: FileList | File[]) => { setLoading(true); setError(undefined); try { const parsed = await parseFiles(Array.from(files)); setLibrary(parsed.parts.length ? parsed : library); setView('dashboard'); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } };
  const common = { parts, filtered, filters, setFilters, selected, setSelected, favorites, toggleFavorite, project, setProject, addProject, compareIds, toggleCompare, settings, setSettings };
  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-20 border-b border-border bg-background/90 backdrop-blur">
      <div className="mx-auto flex max-w-[1600px] items-center justify-between px-5 py-3">
        <div className="flex items-center gap-3"><div className="rounded-xl bg-primary p-2 text-primary-foreground"><Database className="h-6 w-6" /></div><div><h1 className="text-lg font-semibold">CERN KiCad Library Explorer</h1><p className="text-xs text-muted-foreground">Lokales Übersicht- und Suchwerkzeug für Symbole, Footprints und Bauteilvarianten</p></div></div>
        <div className="flex items-center gap-2"><Badge>{stats.parts} Bauteile</Badge><Button onClick={() => setSettings({ ...settings, darkMode: !settings.darkMode })}><Moon className="h-4 w-4" /> Dark</Button></div>
      </div>
    </header>
    <main className="mx-auto grid max-w-[1600px] grid-cols-[250px_1fr] gap-5 px-5 py-5">
      <aside className="sticky top-20 h-[calc(100vh-6rem)] overflow-auto"><nav className="space-y-1">{tabs.map(t => <button key={t.id} onClick={() => setView(t.id)} className={`tab w-full ${view === t.id ? 'tab-active' : ''}`}><t.icon className="h-4 w-4" />{t.label}</button>)}</nav><SafetyNotice /></aside>
      <section className="min-w-0">
        {view === 'import' && <ImportPage importFiles={importFiles} loading={loading} error={error} stats={stats} library={library} />}
        {view === 'dashboard' && <Dashboard parts={parts} stats={stats} />}
        {view === 'explorer' && <Explorer {...common} />}
        {view === 'categories' && <Categories parts={parts} onOpen={(p) => { setSelected(p); setView('explorer'); }} />}
        {view === 'missing' && <Explorer {...common} filtered={parts.filter(p => p.quality !== 'green' || !p.footprint || !p.mpn)} />}
        {view === 'favorites' && <Explorer {...common} filtered={parts.filter(p => favorites.includes(p.id))} />}
        {view === 'project' && <ProjectList parts={parts} project={project} setProject={setProject} />}
        {view === 'compare' && <Compare parts={parts.filter(p => compareIds.includes(p.id))} />}
        {view === 'settings' && <SettingsPage settings={settings} setSettings={setSettings} reset={() => { setLibrary({ ...library, parts: sampleParts, sourceFiles: ['Lokale Beispieldaten'] }); setFavorites([]); setProject([]); }} project={project} />}
      </section>
    </main>
  </div>;
}

function SafetyNotice() { return <Card className="mt-5 p-4 text-xs text-muted-foreground"><strong className="text-foreground">Hinweis:</strong><p className="mt-1">Diese Vorauswahl ersetzt keine elektrische Freigabe. Symbol, Footprint und Pinout müssen vor produktiver Verwendung gegen das Datenblatt geprüft werden.</p></Card>; }
function ImportPage({ importFiles, loading, error, stats, library }: { importFiles: (f: FileList|File[]) => void; loading: boolean; error?: string; stats: ReturnType<typeof summarize>; library: ImportedLibrary }) { return <div className="space-y-5"><Card className="border-dashed p-10 text-center" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); importFiles(e.dataTransfer.files); }}><UploadCloud className="mx-auto h-12 w-12 text-primary" /><h2 className="mt-4 text-2xl font-semibold">CERN KiCad Library importieren</h2><p className="mx-auto mt-2 max-w-2xl text-muted-foreground">Ziehe CERN.sqlite, .kicad_sym, fp-lib-table, sym-lib-table, .kicad_dbl oder JSON/CSV-Dateien hierher. SQLite wird direkt im Browser mit sql.js gelesen; unbekannte Tabellen werden erkannt und gelistet.</p><label className="btn btn-primary mt-5 cursor-pointer"><input type="file" multiple className="hidden" onChange={(e) => e.target.files && importFiles(e.target.files)} />Dateien auswählen</label>{loading && <p className="mt-3 text-sm">Import und Normalisierung laufen…</p>}{error && <pre className="mt-3 whitespace-pre-wrap rounded bg-destructive/10 p-3 text-left text-sm text-destructive">{error}</pre>}</Card><Stats stats={stats} /><Card className="p-4"><h3 className="font-semibold">Importübersicht</h3><p className="mt-2 text-sm text-muted-foreground">Quelle: {library.sourceFiles.join(', ')}</p>{library.tables.length > 0 && <div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-left">Tabelle</th><th className="p-2 text-left">Zeilen</th><th className="p-2 text-left">Spalten</th></tr></thead><tbody>{library.tables.map(t => <tr key={t.name} className="border-b"><td className="p-2">{t.name}</td><td className="p-2">{t.rowCount}</td><td className="p-2">{t.columns.join(', ')}</td></tr>)}</tbody></table></div>}</Card></div>; }
function Stats({ stats }: { stats: ReturnType<typeof summarize> }) { const items = [['Bauteile', stats.parts], ['Symbolbibliotheken', stats.symbolLibraries], ['Footprintbibliotheken', stats.footprintLibraries], ['Kategorien', stats.categories], ['Ohne Footprint', stats.withoutFootprint], ['Ohne MPN', stats.withoutMpn], ['Unvollständig', stats.incomplete]]; return <div className="grid grid-cols-2 gap-3 lg:grid-cols-7">{items.map(([k,v]) => <Card key={k} className="p-4"><p className="text-xs text-muted-foreground">{k}</p><p className="mt-1 text-2xl font-semibold">{v}</p></Card>)}</div>; }
function Dashboard({ parts, stats }: { parts: Part[]; stats: ReturnType<typeof summarize> }) { const count = (key: (p: Part) => string | undefined) => Object.entries(parts.reduce<Record<string, number>>((a,p) => { const k = key(p) || 'Unbekannt'; a[k]=(a[k]||0)+1; return a; }, {})).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value])=>({name,value})); return <div className="space-y-5"><Stats stats={stats} /><div className="grid gap-5 xl:grid-cols-2"><Chart title="Bauteile pro Kategorie" data={count(p=>p.category)} /><Chart title="Bauteile pro Hersteller" data={count(p=>p.manufacturer)} /><PiePanel title="Verteilung SMD/THT/BGA" data={count(p=>p.mount)} /><Chart title="Häufigste Footprintbibliotheken" data={count(p=>p.footprintLibrary)} /><Chart title="Häufigste Symbolbibliotheken" data={count(p=>p.symbolLibrary)} /><PiePanel title="Datenqualität" data={count(p=>p.quality)} /></div></div>; }
function Chart({ title, data }: { title: string; data: {name:string; value:number}[] }) { return <Card className="p-4"><h3 className="mb-3 font-semibold">{title}</h3><ResponsiveContainer width="100%" height={250}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={0.2}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#2563eb" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></Card>; }
function PiePanel({ title, data }: { title: string; data: {name:string; value:number}[] }) { return <Card className="p-4"><h3 className="mb-3 font-semibold">{title}</h3><ResponsiveContainer width="100%" height={250}><PieChart><Tooltip/><Pie data={data} dataKey="value" nameKey="name" outerRadius={90} label>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]} />)}</Pie></PieChart></ResponsiveContainer></Card>; }

type ExplorerProps = { parts: Part[]; filtered: Part[]; filters: FilterState; setFilters: (f: FilterState)=>void; selected?: Part; setSelected: (p?: Part)=>void; favorites: string[]; toggleFavorite: (id:string)=>void; addProject: (id:string)=>void; compareIds: string[]; toggleCompare: (id:string)=>void; settings: AppSettings };
function Explorer(props: ExplorerProps) { const { parts, filtered, filters, setFilters, selected, setSelected } = props; const options = (getter: (p:Part)=>string|number|undefined) => [...new Set(parts.map(getter).filter(Boolean).map(String))].sort(); return <div className="grid grid-cols-[300px_1fr] gap-5"><Card className="h-fit p-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="resistor, MOSFET, Molex, Footprint…" value={filters.query} onChange={e=>setFilters({...filters, query:e.target.value})}/></div><FilterMulti label="Kategorie" values={options(p=>p.category)} selected={filters.categories} onChange={v=>setFilters({...filters,categories:v})}/><FilterMulti label="Symbolbibliothek" values={options(p=>p.symbolLibrary)} selected={filters.symbolLibraries} onChange={v=>setFilters({...filters,symbolLibraries:v})}/><FilterMulti label="Footprintbibliothek" values={options(p=>p.footprintLibrary)} selected={filters.footprintLibraries} onChange={v=>setFilters({...filters,footprintLibraries:v})}/><FilterMulti label="Hersteller" values={options(p=>p.manufacturer)} selected={filters.manufacturers} onChange={v=>setFilters({...filters,manufacturers:v})}/><FilterMulti label="SMD / THT / BGA" values={options(p=>p.mount)} selected={filters.mounts} onChange={v=>setFilters({...filters,mounts:v})}/><FilterMulti label="Package" values={options(p=>p.package)} selected={filters.packages} onChange={v=>setFilters({...filters,packages:v})}/><FilterMulti label="Pins" values={options(p=>p.pins)} selected={filters.pinCounts} onChange={v=>setFilters({...filters,pinCounts:v})}/><Tri label="MPN" value={filters.hasMpn} onChange={v=>setFilters({...filters,hasMpn:v})}/><Tri label="Footprint" value={filters.hasFootprint} onChange={v=>setFilters({...filters,hasFootprint:v})}/><Button className="mt-4 w-full" onClick={()=>setFilters(emptyFilters())}>Filter zurücksetzen</Button></Card><div className="min-w-0 space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Bauteil-Explorer</h2><p className="text-sm text-muted-foreground">{filtered.length} Treffer aus {parts.length} Datensätzen</p></div><div className="flex gap-2"><Button onClick={()=>downloadText('treffer.json', JSON.stringify(filtered, null, 2), 'application/json')}><Download className="h-4 w-4"/>JSON</Button><Button onClick={()=>downloadText('treffer.csv', toCsv(filtered.map(flatPart)), 'text/csv')}><FileDown className="h-4 w-4"/>CSV</Button></div></div><PartTable {...props} parts={filtered} onSelect={setSelected} />{selected && <Detail part={selected} {...props} close={()=>setSelected(undefined)} />}</div></div>; }
function FilterMulti({ label, values, selected, onChange }: { label:string; values:string[]; selected:string[]; onChange:(v:string[])=>void }) { if (!values.length) return null; return <div className="mt-4"><p className="mb-2 text-xs font-medium uppercase text-muted-foreground">{label}</p><div className="max-h-36 space-y-1 overflow-auto">{values.map(v=><label key={v} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(v)} onChange={e=>onChange(e.target.checked?[...selected,v]:selected.filter(x=>x!==v))}/><span className="truncate">{v}</span></label>)}</div></div>; }
function Tri({ label, value, onChange }: { label:string; value?:boolean; onChange:(v?:boolean)=>void }) { return <div className="mt-4"><p className="mb-2 text-xs font-medium uppercase text-muted-foreground">{label}</p><Select value={value === undefined ? 'all' : value ? 'yes':'no'} onChange={e=>onChange(e.target.value==='all'?undefined:e.target.value==='yes')}><option value="all">Alle</option><option value="yes">vorhanden</option><option value="no">fehlt</option></Select></div>; }
function PartTable({ parts, onSelect, favorites, toggleFavorite, addProject, compareIds, toggleCompare, settings }: ExplorerProps & { onSelect:(p:Part)=>void }) { const [sort, setSort] = useState<keyof Part>('name'); const shown = [...parts].sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''))).slice(0, 500); const cols: [keyof Part|string,string][] = [['name','Name'],['description','Beschreibung'],['category','Kategorie'],['manufacturer','Hersteller'],['mpn','MPN'],['value','Wert'],['symbol','Symbol'],['footprint','Footprint'],['package','Package'],['pins','Pins'],['quality','Status']]; return <Card className="overflow-hidden"><div className="overflow-auto"><table className={`w-full text-left ${settings.compactTable?'text-xs':'text-sm'}`}><thead className="sticky top-0 bg-muted"><tr>{cols.filter(([c])=>settings.visibleColumns.includes(String(c))).map(([c,l])=><th key={String(c)} className="whitespace-nowrap p-2 font-medium"><button onClick={()=>setSort(c as keyof Part)}>{l}</button></th>)}<th className="p-2">Aktionen</th></tr></thead><tbody>{shown.map(p=><tr key={p.id} className="cursor-pointer border-b border-border hover:bg-muted/60" onClick={()=>onSelect(p)}>{cols.filter(([c])=>settings.visibleColumns.includes(String(c))).map(([c])=><td key={String(c)} className="max-w-[260px] truncate p-2">{c==='quality'?<QualityBadge quality={p.quality}/>:String(p[c as keyof Part]??'')}</td>)}<td className="whitespace-nowrap p-2" onClick={e=>e.stopPropagation()}><Button onClick={()=>toggleFavorite(p.id)}>{favorites.includes(p.id)?<Heart className="h-4 w-4 fill-current"/>:<Heart className="h-4 w-4"/>}</Button><Button onClick={()=>addProject(p.id)}><Plus className="h-4 w-4"/></Button><Button onClick={()=>toggleCompare(p.id)} disabled={!compareIds.includes(p.id)&&compareIds.length>=5}><GitCompare className={`h-4 w-4 ${compareIds.includes(p.id)?'text-primary':''}`}/></Button></td></tr>)}</tbody></table></div>{parts.length>500&&<p className="p-3 text-xs text-muted-foreground">Aus Performancegründen werden die ersten 500 Treffer angezeigt. Bitte Filter verfeinern.</p>}</Card>; }
function Detail({ part, close, favorites, toggleFavorite, addProject }: { part: Part; close:()=>void; favorites:string[]; toggleFavorite:(id:string)=>void; addProject:(id:string)=>void }) { const copy = (text?: string) => text && navigator.clipboard?.writeText(text); return <Card className="fixed right-5 top-20 z-30 h-[calc(100vh-6rem)] w-[520px] overflow-auto p-5 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">{part.name}</h2><p className="mt-1 text-sm text-muted-foreground">{part.description}</p></div><Button onClick={close}>Schließen</Button></div><div className="mt-4 flex gap-2"><QualityBadge quality={part.quality}/><Badge>{part.category}</Badge>{part.subcategory&&<Badge>{part.subcategory}</Badge>}</div><div className="mt-5 grid grid-cols-2 gap-3 text-sm">{[['Hersteller',part.manufacturer],['MPN',part.mpn],['Value',part.value],['Symbol',part.symbol],['Footprint',part.footprint],['Package',part.package],['Pins',part.pins],['Mount',part.mount]].map(([k,v])=><div key={k} className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{k}</p><p className="break-words font-medium">{String(v??'—')}</p></div>)}</div><h3 className="mt-5 font-semibold">Aktionen</h3><div className="mt-2 flex flex-wrap gap-2"><Button onClick={()=>copy(`${part.symbol ?? part.name} ${part.footprint ?? ''}`)}>KiCad-Suchbegriff kopieren</Button><Button onClick={()=>copy(part.mpn)}>MPN kopieren</Button><Button onClick={()=>copy(part.footprint)}>Footprint kopieren</Button><Button onClick={()=>copy(part.symbol)}>Symbol kopieren</Button><Button onClick={()=>toggleFavorite(part.id)}><Star className="h-4 w-4"/>{favorites.includes(part.id)?'Favorit entfernen':'Als Favorit'}</Button><Button onClick={()=>addProject(part.id)}>Zur Projektliste</Button></div><h3 className="mt-5 font-semibold">Warnungen</h3><ul className="mt-2 space-y-1 text-sm">{part.warnings.map(w=><li key={w} className="rounded bg-amber-500/10 p-2 text-amber-700 dark:text-amber-300">{w}</li>)}</ul><h3 className="mt-5 font-semibold">Technische Parameter</h3><pre className="mt-2 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(part.parameters, null, 2)}</pre><h3 className="mt-5 font-semibold">Rohfelder</h3><pre className="mt-2 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(part.raw, null, 2)}</pre></Card>; }
function Categories({ parts, onOpen }: { parts: Part[]; onOpen:(p:Part)=>void }) { const groups = Object.entries(parts.reduce<Record<string, Part[]>>((a,p)=>{(a[p.category]??=[]).push(p); return a;},{})).sort((a,b)=>a[0].localeCompare(b[0])); return <div className="grid gap-4 lg:grid-cols-2">{groups.map(([cat, list])=><Card key={cat} className="p-4"><h3 className="font-semibold">{cat} <Badge>{list.length}</Badge></h3><div className="mt-3 flex flex-wrap gap-2">{[...new Set(list.map(p=>p.subcategory).filter(Boolean))].map(s=><Badge key={s}>{s}</Badge>)}</div><div className="mt-3 space-y-1">{list.slice(0,8).map(p=><button key={p.id} onClick={()=>onOpen(p)} className="block w-full rounded p-2 text-left text-sm hover:bg-muted">{p.name}</button>)}</div></Card>)}</div>; }
function ProjectList({ parts, project, setProject }: { parts: Part[]; project: ProjectItem[]; setProject:(p:ProjectItem[])=>void }) { const rows = project.map(i=>({ item:i, part:parts.find(p=>p.id===i.partId)})).filter(x=>x.part); return <Card className="p-4"><div className="mb-4 flex justify-between"><h2 className="text-xl font-semibold">Projektliste</h2><div className="flex gap-2"><Button onClick={()=>downloadText('projektliste.json', JSON.stringify(project,null,2),'application/json')}>JSON Export</Button><Button onClick={()=>downloadText('projektliste.csv', toCsv(rows.map(r=>flatPart(r.part!))),'text/csv')}>CSV Export</Button></div></div><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-left">Name</th><th>MPN</th><th>Footprint</th><th>Symbol</th><th>Notiz</th><th></th></tr></thead><tbody>{rows.map(({item,part})=><tr key={item.partId} className="border-b"><td className="p-2">{part!.name}</td><td>{part!.mpn}</td><td>{part!.footprint}</td><td>{part!.symbol}</td><td><Input value={item.note} onChange={e=>setProject(project.map(x=>x.partId===item.partId?{...x,note:e.target.value}:x))}/></td><td><Button variant="destructive" onClick={()=>setProject(project.filter(x=>x.partId!==item.partId))}><Trash2 className="h-4 w-4"/></Button></td></tr>)}</tbody></table></Card>; }
function Compare({ parts }: { parts: Part[] }) { if (parts.length < 2) return <Card className="p-8 text-center text-muted-foreground">Bitte 2 bis 5 Bauteile im Explorer für den Vergleich auswählen.</Card>; const rows = ['name','category','manufacturer','mpn','footprint','package','pins','quality','description'] as (keyof Part)[]; return <Card className="overflow-auto p-4"><h2 className="mb-4 text-xl font-semibold">Vergleichsansicht</h2><table className="w-full text-sm"><tbody>{rows.map(r=><tr key={r} className="border-b"><th className="p-2 text-left capitalize">{r}</th>{parts.map(p=><td key={p.id} className="min-w-[220px] p-2 align-top">{r==='quality'?<QualityBadge quality={p.quality}/>:String(p[r]??'—')}</td>)}</tr>)}<tr><th className="p-2 text-left">Parameter</th>{parts.map(p=><td key={p.id} className="p-2"><pre className="text-xs">{JSON.stringify(p.parameters,null,2)}</pre></td>)}</tr></tbody></table></Card>; }
function SettingsPage({ settings, setSettings, reset, project }: { settings:AppSettings; setSettings:(s:AppSettings)=>void; reset:()=>void; project:ProjectItem[] }) { const allCols = ['name','description','category','manufacturer','mpn','value','symbol','footprint','package','pins','quality']; return <div className="space-y-4"><Card className="p-4"><h2 className="text-xl font-semibold">Einstellungen</h2><label className="mt-4 flex items-center gap-2"><input type="checkbox" checked={settings.darkMode} onChange={e=>setSettings({...settings,darkMode:e.target.checked})}/> Dark Mode</label><label className="mt-2 flex items-center gap-2"><input type="checkbox" checked={settings.compactTable} onChange={e=>setSettings({...settings,compactTable:e.target.checked})}/> Kompakte Tabellenansicht</label></Card><Card className="p-4"><h3 className="font-semibold">Spalten</h3><div className="mt-2 grid grid-cols-3 gap-2">{allCols.map(c=><label key={c} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.visibleColumns.includes(c)} onChange={e=>setSettings({...settings,visibleColumns:e.target.checked?[...settings.visibleColumns,c]:settings.visibleColumns.filter(x=>x!==c)})}/>{c}</label>)}</div></Card><Card className="p-4"><h3 className="font-semibold">Datenqualität-Regeln</h3>{Object.entries(settings.qualityRules).map(([k,v])=><label key={k} className="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={v} onChange={e=>setSettings({...settings,qualityRules:{...settings.qualityRules,[k]:e.target.checked}})}/>{k}</label>)}</Card><Card className="p-4"><h3 className="font-semibold">Datenverwaltung</h3><div className="mt-3 flex flex-wrap gap-2"><Button variant="destructive" onClick={reset}>Importdaten/Favoriten zurücksetzen</Button><Button onClick={()=>downloadText('projektliste.json', JSON.stringify(project,null,2),'application/json')}>Projektliste exportieren</Button></div><p className="mt-3 text-sm text-muted-foreground">Spaltenzuordnung wird beim Import über Alias-Regeln automatisch vorgenommen; unbekannte SQLite-Tabellen werden auf der Importseite angezeigt.</p></Card></div>; }
function flatPart(p: Part): Record<string, unknown> { return { name:p.name, description:p.description, category:p.category, manufacturer:p.manufacturer, mpn:p.mpn, value:p.value, symbol:p.symbol, footprint:p.footprint, package:p.package, pins:p.pins, quality:p.quality }; }

createRoot(document.getElementById('root')!).render(<App />);
